
stages:
  - validate
  - deploy

validate_website:
  stage: validate
  image: alpine:latest
  script:
    - test -f index.html
    - test -f about.html
    - test -f contact.html
    - test -f portfolio.html
    - test -f services.html
    - test -d css
    - test -d js
    - test -f css/style.css
    - test -f js/main.js
    - echo "Website validation successful"

deploy_to_netlify:
  stage: deploy
  image: node:20-alpine
  before_script:
    - npm install -g netlify-cli
  script:
    - netlify deploy --prod --dir=. --site="$220078fe-f433-45c6-8c4d-80628ba2e46d"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'